<?php
/**
 * TicketApiTest
 * PHP version 5
 *
 * @category Class
 * @package  UvdeskApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Uvdesk api
 *
 * The UVdesk API correlates with the Representational State Transfer category (REST) that allows to perform several actions like reading, editing, deleting, adding data of the helpdesk system. Here, we are using subdomain in base path and Token Url. user must modify subdomain to his/her uvdesk subdomain for api access. If you want to download and use api client from top right section. Also then, you must replace subdomain with your subdomain name at uvdesk in downloaded client's baseUrl.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@uvdesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace UvdeskApi;

use \UvdeskApi\Configuration;
use \UvdeskApi\ApiException;
use \UvdeskApi\ObjectSerializer;

/**
 * TicketApiTest Class Doc Comment
 *
 * @category Class
 * @package  UvdeskApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TicketApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteApiTicket
     *
     * Delete a given ticket.
     *
     */
    public function testDeleteApiTicket()
    {
    }

    /**
     * Test case for deleteApiTicketCollaborator
     *
     * Remove collaborator from Ticket.
     *
     */
    public function testDeleteApiTicketCollaborator()
    {
    }

    /**
     * Test case for getApiTicket
     *
     * View a ticket.
     *
     */
    public function testGetApiTicket()
    {
    }

    /**
     * Test case for getApiTicketAttachment
     *
     * download attachment.
     *
     */
    public function testGetApiTicketAttachment()
    {
    }

    /**
     * Test case for patchApiTicket
     *
     * Edit given ticket's properties.
     *
     */
    public function testPatchApiTicket()
    {
    }

    /**
     * Test case for postApiTicketCollaborator
     *
     * Add collaborator for Ticket.
     *
     */
    public function testPostApiTicketCollaborator()
    {
    }

    /**
     * Test case for putApiTicket
     *
     * Edit given ticket.
     *
     */
    public function testPutApiTicket()
    {
    }
}
